// Pflanzendaten für den Pflanzen-Shop
const PLANTS = [
  {
    id: "5938",
    name: "Monstera Klein",
    category: "Monstera",
    image: "images/IMG_5938.jpg",
    size: "Klein",
    care: "Mittel",
    light: "Hell, indirektes Licht",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Junge Monstera deliciosa mit den ersten typischen Fensterblättern.",
    desc: "Die Monstera deliciosa ist einer der beliebtesten Zimmerpflanzen-Klassiker. Diese kleine Pflanze steht noch am Anfang ihrer Entwicklung – die charakteristischen Löcher und Einschnitte in den Blättern (Fensterung) bilden sich erst mit zunehmendem Alter aus. Sie bevorzugt einen hellen Platz ohne pralle Mittagssonne und mag es, wenn die oberste Erdschicht zwischen den Wassergaben leicht antrocknet. Im Winter braucht sie deutlich weniger Wasser als im Sommer. Ein Rankgitter oder Moosstab hilft ihr später beim Wachsen."
  },
  {
    id: "5939",
    name: "Monstera Mittel",
    category: "Monstera",
    image: "images/IMG_5939.jpg",
    size: "Mittel",
    care: "Mittel",
    light: "Hell, indirektes Licht",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Kräftige Monstera deliciosa mit mehreren großen, gefensterten Blättern.",
    desc: "Diese Monstera deliciosa ist schon etwas weiter gewachsen und zeigt die typischen tiefen Einschnitte in den Blättern. Sie wächst zügig, wenn sie einen hellen, warmen Standort ohne direkte Sonne bekommt. Gegossen wird, sobald sich die oberen 2–3 cm der Erde trocken anfühlen – im Winter reicht meist alle 2 bis 3 Wochen. Gelegentliches Abstauben der großen Blätter fördert die Photosynthese und beugt Schädlingen vor."
  },
  {
    id: "5940",
    name: "Monstera Adansonii",
    category: "Monstera",
    image: "images/IMG_5940.jpg",
    size: "Klein",
    care: "Mittel",
    light: "Hell, indirektes Licht",
    waterWinter: "alle 2 Wochen",
    shortDesc: "Fensterblatt mit filigranen, stark durchlöcherten Blättern – rankt gerne.",
    desc: "Die Monstera adansonii, auch Fensterblatt genannt, unterscheidet sich von der klassischen Monstera durch ihre kleineren, dicht durchlöcherten Blätter und die stark rankende Wuchsform. Sie liebt es hell und luftfeucht, aber ohne direkte Sonne. An einer Rankhilfe oder einem Moosstab klettert sie besonders schön in die Höhe. Die Erde sollte leicht feucht gehalten werden, im Winter genügt es, etwa alle zwei Wochen zu gießen."
  },
  {
    id: "5948",
    name: "Monstera Thai Constellation",
    category: "Monstera",
    image: "images/IMG_5948.jpg",
    size: "Mittel",
    care: "Hoch",
    light: "Hell, indirektes Licht (keine pralle Sonne)",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Seltene, panaschierte Monstera-Variante mit cremeweißer Marmorierung.",
    desc: "Die Monstera Thai Constellation ist eine besonders gefragte, panaschierte Sorte mit cremeweißer bis gelblicher Marmorierung auf dunkelgrünem Blattgrund. Da ihr die weißen Blattbereiche keine Photosynthese ermöglichen, wächst sie langsamer als eine normale Monstera und ist etwas anspruchsvoller in der Pflege. Sie braucht einen hellen Standort ganz ohne direkte Sonne, da die hellen Blattpartien sonst leicht verbrennen. Staunässe unbedingt vermeiden – lieber etwas seltener, dafür gründlich gießen."
  },
  {
    id: "5949",
    name: "Monstera Groß",
    category: "Monstera",
    image: "images/IMG_5949.jpg",
    size: "Groß",
    care: "Mittel",
    light: "Hell, indirektes Licht",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Ausgewachsene Monstera deliciosa mit großen, stark gefensterten Blättern.",
    desc: "Diese ausgewachsene Monstera deliciosa besticht mit großen, tief eingeschnittenen und gefensterten Blättern. Sie braucht mittlerweile etwas mehr Platz und Wasser als eine junge Pflanze, sollte aber weiterhin nur gegossen werden, wenn die Erde angetrocknet ist. Ein heller Standort ohne direkte Mittagssonne und gelegentliches Düngen in der Wachstumsphase lassen sie prächtig gedeihen. Im Winter wird die Wassergabe deutlich reduziert."
  },
  {
    id: "5935",
    name: "Euphorbia Trigona Groß",
    category: "Wolfsmilch",
    image: "images/IMG_5935.jpg",
    size: "Groß",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 5–6 Wochen",
    shortDesc: "Große, stark verzweigte Wolfsmilch-Säule – sieht aus wie ein Kaktus.",
    desc: "Die Euphorbia trigona (Dreikantige Wolfsmilch) wird oft mit einem Kaktus verwechselt, ist botanisch aber eine Sukkulente aus der Wolfsmilchfamilie. Diese große, stark verzweigte Pflanze ist absolut pflegeleicht: Sie liebt einen sonnigen, warmen Platz und übersteht auch mal längere Trockenphasen problemlos. Im Winter reicht es, alle 5 bis 6 Wochen sparsam zu gießen. Vorsicht beim Umtopfen: Der milchige Pflanzensaft ist hautreizend, am besten Handschuhe tragen."
  },
  {
    id: "5941",
    name: "Euphorbia Trigona Steckling",
    category: "Wolfsmilch",
    image: "images/IMG_5941.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 5–6 Wochen",
    shortDesc: "Junger Ableger der Dreikantigen Wolfsmilch, noch mit wenigen Trieben.",
    desc: "Dieser junge Steckling der Euphorbia trigona hat gerade erst begonnen, sich zu verzweigen. Wie alle Wolfsmilchgewächse ist er extrem genügsam und verzeiht auch mal vergessenes Gießen. Ein sonniger Platz fördert kompaktes, kräftiges Wachstum. Gegossen wird sparsam und nur, wenn die Erde komplett durchgetrocknet ist – im Winter reicht das etwa alle 5 bis 6 Wochen."
  },
  {
    id: "5943",
    name: "Euphorbia Trigona Mittel",
    category: "Wolfsmilch",
    image: "images/IMG_5943.jpg",
    size: "Mittel",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 5–6 Wochen",
    shortDesc: "Schlanke, aufrecht wachsende Wolfsmilchsäule mit dekorativen Kanten.",
    desc: "Diese mittelgroße Euphorbia trigona wächst schön aufrecht mit den typischen drei- bis vierkantigen, dornbesetzten Trieben. Sie ist ideal für sonnige Fensterplätze und braucht kaum Pflege. In der Wachstumsphase im Sommer darf gelegentlich gegossen und leicht gedüngt werden, im Winter reicht eine sehr sparsame Wassergabe alle paar Wochen."
  },
  {
    id: "5944",
    name: "Euphorbia Trigona Klein",
    category: "Wolfsmilch",
    image: "images/IMG_5944.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 5–6 Wochen",
    shortDesc: "Kompakte, kleinere Wolfsmilchsäule mit hellen Dornenreihen.",
    desc: "Eine kompakte, etwas kürzer gewachsene Euphorbia trigona mit gut sichtbaren, hellen Dornenreihen entlang der Kanten. Auch sie ist eine pflegeleichte Sukkulente, die einen sonnigen Standort und wenig Gießen bevorzugt. Staunässe sollte unbedingt vermieden werden, ein durchlässiges Kakteensubstrat ist ideal."
  },
  {
    id: "5954",
    name: "Euphorbia Trigona Hoch",
    category: "Wolfsmilch",
    image: "images/IMG_5954.jpg",
    size: "Groß",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 5–6 Wochen",
    shortDesc: "Hoch aufragende, schlanke Wolfsmilch mit mehreren dünnen Trieben.",
    desc: "Diese Euphorbia trigona ist besonders hoch und schlank gewachsen, mit mehreren dünnen, aufrechten Trieben. Je heller und sonniger der Standort, desto kompakter und stabiler bleibt das Wachstum. Wie alle Wolfsmilchgewächse ist sie sehr genügsam beim Gießen – im Winter genügt es, die Pflanze nur alle 5 bis 6 Wochen leicht zu wässern."
  },
  {
    id: "5936",
    name: "Aloe Vera Gruppe",
    category: "Aloe Vera",
    image: "images/IMG_5936.jpg",
    size: "Mittel",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 4 Wochen",
    shortDesc: "Mehrere Aloe-Vera-Pflanzen zusammen an einem hellen Fensterplatz.",
    desc: "Diese Gruppe aus mehreren Aloe-Vera-Töpfen zeigt, wie unkompliziert sich Aloe Vera vermehren und gruppieren lässt. Alle Pflanzen lieben einen möglichst sonnigen, warmen Standort, zum Beispiel ein Südfenster. Gegossen wird erst, wenn die Erde komplett trocken ist – Staunässe verträgt Aloe Vera gar nicht. Der Gel-Inhalt der Blätter wird traditionell für Haut und Wunden verwendet."
  },
  {
    id: "5937",
    name: "Aloe Vera Klein",
    category: "Aloe Vera",
    image: "images/IMG_5937.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 4 Wochen",
    shortDesc: "Kleine, kompakte Aloe Vera mit charakteristischen weißen Flecken.",
    desc: "Diese junge Aloe Vera zeigt noch die für jüngere Pflanzen typischen weißen Sprenkel auf den Blättern. Sie ist denkbar pflegeleicht: viel Sonne, wenig Wasser. Im Winter reicht es völlig, sie alle vier Wochen leicht zu gießen. In der prallen Mittagssonne am Fenster fühlt sie sich am wohlsten."
  },
  {
    id: "5953",
    name: "Aloe Vera Mittel",
    category: "Aloe Vera",
    image: "images/IMG_5953.jpg",
    size: "Mittel",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 4 Wochen",
    shortDesc: "Bereits kräftiger gewachsene Aloe Vera mit dicken, fleischigen Blättern.",
    desc: "Diese Aloe Vera hat schon deutlich dickere, fleischigere Blätter entwickelt – ein Zeichen für einen guten, sonnigen Standort. Sie speichert Wasser in ihren Blättern und kommt daher auch mit unregelmäßigem Gießen gut zurecht. Im Winter sollte die Wassergabe auf ein Minimum reduziert werden, etwa alle vier Wochen."
  },
  {
    id: "5942",
    name: "Geldbaum",
    category: "Sonstige",
    image: "images/IMG_5942.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Viel Sonne / sehr helles Licht",
    waterWinter: "alle 4 Wochen",
    shortDesc: "Crassula ovata mit dicken, runden Blättern – gilt als Glücksbringer.",
    desc: "Der Geldbaum (Crassula ovata) ist eine robuste Sukkulente mit dicken, glänzenden, ovalen Blättern und gilt traditionell als Glücksbringer. Er bevorzugt einen hellen bis sonnigen Standort und speichert Wasser in seinen Blättern, weshalb er sehr genügsam beim Gießen ist. Im Winter reicht eine Wassergabe etwa alle vier Wochen völlig aus – zu viel Wasser lässt die Wurzeln schnell faulen."
  },
  {
    id: "5945",
    name: "Strelitzie",
    category: "Sonstige",
    image: "images/IMG_5945.jpg",
    size: "Groß",
    care: "Mittel",
    light: "Hell, auch direkte Sonne",
    waterWinter: "alle 2 Wochen",
    shortDesc: "Große Strelitzia nicolai mit bananenblattartigen Blättern – echter Blickfang.",
    desc: "Die Strelitzia nicolai (Bananen-Strelitzie) ist mit ihren großen, paddelförmigen Blättern ein imposanter Blickfang und kann als Zimmerpflanze mehrere Meter hoch werden. Sie braucht viel Licht, verträgt auch direkte Sonne, und in der Wachstumsphase regelmäßig Wasser und Dünger. Im Winter wird deutlich sparsamer gegossen, etwa alle zwei Wochen. Zugluft und ständige Standortwechsel mag sie nicht."
  },
  {
    id: "5946",
    name: "Grünlilie Mittel",
    category: "Grünlilie",
    image: "images/IMG_5946.jpg",
    size: "Mittel",
    care: "Niedrig",
    light: "Hell bis Halbschatten",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Buschige, panaschierte Grünlilie mit weiß-grün gestreiften Blättern.",
    desc: "Die Grünlilie (Chlorophytum comosum) zählt zu den pflegeleichtesten und robustesten Zimmerpflanzen überhaupt und filtert nebenbei effektiv die Raumluft. Sie kommt sowohl mit hellen als auch etwas schattigeren Standorten gut zurecht. Gegossen wird mäßig, sobald die Erde angetrocknet ist. Mit der Zeit bildet sie an langen Trieben kleine 'Kindel', die sich leicht als neue Pflanzen abtrennen lassen."
  },
  {
    id: "5947",
    name: "Grünlilie Klein",
    category: "Grünlilie",
    image: "images/IMG_5947.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Hell bis Halbschatten",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Junge Grünlilie mit schmalen, überhängenden Blättern.",
    desc: "Diese junge Grünlilie zeigt bereits die schmalen, überhängenden Blätter, die typisch für die Art sind. Sie ist extrem anpassungsfähig und verzeiht auch mal eine vergessene Gießrunde. Ein Platz mit hellem bis halbschattigem Licht und mäßiges Gießen reichen für gutes Wachstum völlig aus."
  },
  {
    id: "5952",
    name: "Efeutute Klein",
    category: "Efeutute",
    image: "images/IMG_5952.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Halbschatten bis hell",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Buschige Efeutute (Pothos) mit herzförmigen, glänzenden Blättern.",
    desc: "Die Efeutute (Epipremnum aureum), auch Pothos genannt, ist eine der pflegeleichtesten Rank- und Hängepflanzen. Sie kommt sowohl mit hellen als auch mit schattigeren Standorten zurecht und verzeiht kleinere Pflegefehler locker. Gegossen wird, sobald die Erde angetrocknet ist. An einer Rankhilfe wächst sie in die Höhe, ohne Stütze bildet sie lange, hängende Triebe."
  },
  {
    id: "5956",
    name: "Efeutute Groß",
    category: "Efeutute",
    image: "images/IMG_5956.jpg",
    size: "Groß",
    care: "Niedrig",
    light: "Halbschatten bis hell",
    waterWinter: "alle 2–3 Wochen",
    shortDesc: "Ausgewachsene Efeutute mit langen, weit herabhängenden Ranken.",
    desc: "Diese ausgewachsene Efeutute hat bereits beeindruckend lange Ranken entwickelt, die sich wunderbar von einem Regal oder Hängetopf herabhängen lassen. Sie ist äußerst pflegeleicht und toleriert auch schattigere Standorte, wächst aber an einem helleren Platz zügiger. Gegossen wird mäßig, wenn die Erde angetrocknet ist – im Winter reicht das etwa alle zwei bis drei Wochen."
  },
  {
    id: "5950",
    name: "Avocado-Pflanze",
    category: "Sonstige",
    image: "images/IMG_5950.jpg",
    size: "Klein",
    care: "Mittel",
    light: "Hell, keine pralle Mittagssonne",
    waterWinter: "alle 1–2 Wochen",
    shortDesc: "Aus einem Kern selbst gezogene, junge Avocadopflanze.",
    desc: "Diese Avocadopflanze wurde aus einem Kern gezogen und zeigt schon die ersten kräftigen Blätter. Sie mag einen hellen, warmen Standort ohne pralle Mittagssonne und gleichmäßig feuchte, aber nicht nasse Erde. Avocadopflanzen wachsen recht schnell und sollten regelmäßig umgetopft werden, sobald der Topf zu klein wird. Trockene Heizungsluft im Winter mag sie gar nicht – gelegentliches Besprühen der Blätter hilft."
  },
  {
    id: "5951",
    name: "Drachenbaum",
    category: "Sonstige",
    image: "images/IMG_5951.jpg",
    size: "Mittel",
    care: "Niedrig",
    light: "Hell bis Halbschatten",
    waterWinter: "alle 3 Wochen",
    shortDesc: "Dracaena marginata mit schmalen, rot gerandeten Blättern.",
    desc: "Der Drachenbaum (Dracaena marginata) ist eine robuste, sehr pflegeleichte Zimmerpflanze mit schmalen, spitz zulaufenden Blättern, die oft einen rötlichen Rand zeigen. Er kommt mit hellen bis leicht schattigen Standorten gut zurecht und verträgt problemlos trockene Heizungsluft. Gegossen wird sparsam, sobald die Erde angetrocknet ist – im Winter reicht meist alle drei Wochen."
  },
  {
    id: "5955",
    name: "Glücksbambus",
    category: "Sonstige",
    image: "images/IMG_5955.jpg",
    size: "Klein",
    care: "Niedrig",
    light: "Halbschatten, kein direktes Sonnenlicht",
    waterWinter: "Wasser alle 1–2 Wochen wechseln",
    shortDesc: "Dracaena sanderiana in der Vase – wächst direkt im Wasser.",
    desc: "Der Glücksbambus (Dracaena sanderiana) ist botanisch gar kein Bambus, wächst aber genauso unkompliziert – meist direkt in einer Vase mit Wasser statt in Erde. Er mag einen hellen Platz ohne direkte Sonneneinstrahlung. Statt zu gießen wird regelmäßig, etwa alle ein bis zwei Wochen, das Wasser in der Vase gewechselt, um Fäulnis und Algenbildung vorzubeugen. Kalkarmes, abgestandenes Wasser ist ideal."
  }
];
